# Generated by Django 5.1.4 on 2025-03-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_skindiagnosis_cid_skindiagnosis_diagnosis_result"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skindiagnosis",
            name="cid",
        ),
        migrations.RemoveField(
            model_name="skindiagnosis",
            name="diagnosis_result",
        ),
    ]
