# Generated by Django 5.1.4 on 2025-03-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_skindiagnosis_cid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
