# Generated by Django 5.1.4 on 2025-03-20 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userprofile_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="full_name",
        ),
    ]
