# Generated by Django 5.1.4 on 2025-03-20 08:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_diagnosis_cid_skindiagnosis_cid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="cid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="skindiagnosis",
            name="cid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
