# Generated by Django 5.1.4 on 2025-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_diagnosis_cid_alter_skindiagnosis_cid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="cid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="skindiagnosis",
            name="cid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
