# Generated by Django 5.1.4 on 2025-01-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerinfo",
            name="poster",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
    ]
