# Generated by Django 5.1.4 on 2025-01-15 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_playerinfo_poster"),
    ]

    operations = [
        migrations.CreateModel(
            name="playerhistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preclub", models.CharField(max_length=250)),
                ("current_club", models.CharField(max_length=25)),
                (
                    "fav_club",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.playerinfo",
                    ),
                ),
            ],
        ),
    ]
