# Generated by Django 5.1.4 on 2025-01-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_playerhistory_fav_club_playerinfo_fav_club"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerinfo",
            name="rumor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playerinfo_rumor",
                to="products.playerhistory",
            ),
        ),
        migrations.AlterField(
            model_name="playerinfo",
            name="fav_club",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playerinfo_fav_club",
                to="products.playerhistory",
            ),
        ),
    ]
