# Generated by Django 5.1.4 on 2025-01-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_playerinfo_rumor_alter_playerinfo_fav_club"),
    ]

    operations = [
        migrations.CreateModel(
            name="coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="playerinfo",
            name="rumor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playerinfo_rumor",
                to="products.coach",
            ),
        ),
    ]
