# Generated by Django 5.1.4 on 2025-01-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_coach_alter_playerinfo_rumor"),
    ]

    operations = [
        migrations.CreateModel(
            name="transferfee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee", models.ImageField(max_length=20, upload_to="")),
            ],
        ),
        migrations.AddField(
            model_name="playerinfo",
            name="transferfees",
            field=models.ManyToManyField(
                related_name="fee_paid", to="products.transferfee"
            ),
        ),
    ]
