# Generated by Django 5.1.4 on 2025-01-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_transferfee_playerinfo_transferfees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transferfee",
            name="fee",
            field=models.CharField(max_length=20),
        ),
    ]
