# Generated by Django 5.1.4 on 2025-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_transferfee_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerinfo",
            name="fav_club",
        ),
        migrations.AlterField(
            model_name="playerinfo",
            name="poster",
            field=models.ImageField(upload_to="images/"),
        ),
        migrations.DeleteModel(
            name="playerhistory",
        ),
    ]
