# Generated by Django 5.1.4 on 2025-01-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0009_remove_playerinfo_fav_club_alter_playerinfo_poster_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="playerhistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preclub", models.CharField(max_length=250)),
                ("current_club", models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name="playerinfo",
            name="fav_club",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playerinfo_fav_club",
                to="products.playerhistory",
            ),
        ),
    ]
