# Generated by Django 5.1.4 on 2025-03-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
